name: hardcraft
version: '0.8.8'
main: dev.lrdcxdes.hardcraft.Hardcraft
api-version: '1.21'
load: POSTWORLD
author: lrdcxdes
description: Hardcraft core plugin


commands:
  race:
    description: Unset race
    usage: /race
    permission: hardcraft.admin
  group:
    description: Set player group
    usage: /group
    permission: hardcraft.admin
  economy:
    aliases: [ eco ]
    description: Admin command to manage player balance
    usage: /economy <set|add|remove> <player> <amount>
    permission: hardcraft.admin
  pay:
    description: Pay another player
    usage: /pay <player> <amount>
  balance:
    description: Check your balance
    aliases: [ bal ]
    usage: /balance
  friends:
    description: Manage your friends list
    usage: /friends <list|add|remove|accept|deny> [player]
    aliases: [ friend, f ]
  shop:
    aliases: [ market, magazine ]
    description: Open Shop
    usage: /shop [all]